setono_sylius_stock_movement_admin_stock_movement:
    resource: |
        alias: setono_sylius_stock_movement.stock_movement
        only: ['show', 'index']
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: setono_sylius_stock_movement_admin_stock_movement
        vars:
            all:
                subheader: setono_sylius_stock_movement.ui.manage_stock_movements
            index:
                icon: 'chart bar'
    type: sylius.resource
    
setono_sylius_stock_movement_admin_report_configuration:
    resource: |
        alias: setono_sylius_stock_movement.report_configuration
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: setono_sylius_stock_movement_admin_report_configuration
        vars:
            all:
                subheader: setono_sylius_stock_movement.ui.manage_report_configurations
                templates:
                    form: "@SetonoSyliusStockMovementPlugin/ReportConfiguration/_form.html.twig"
            index:
                icon: 'chart bar'
    type: sylius.resource
    
setono_sylius_stock_movement_admin_report:
    resource: |
        alias: setono_sylius_stock_movement.report
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: setono_sylius_stock_movement_admin_report
        vars:
            all:
                subheader: setono_sylius_stock_movement.ui.manage_reports
            index:
                icon: 'chart bar'
    type: sylius.resource
    
setono_sylius_stock_movement_admin_report_show:
    path: /reports/{id}
    methods: [GET]
    defaults:
        _controller: setono_sylius_stock_movement.controller.report:showAction
        _sylius:
            section: admin
            permission: true
            template: "@SetonoSyliusStockMovementPlugin/Report/show.html.twig"
            

setono_sylius_stock_movement_admin_report_configuration_process:
    path: /report-configurations/process/{id}
    methods: [GET]
    defaults:
        _controller: setono_sylius_stock_movement.controller.action.process_report_configuration
        _sylius:
            section: admin
            permission: true
            
setono_sylius_stock_movement_admin_report_download:
    path: /reports/download/{id}
    methods: [GET]
    defaults:
        _controller: setono_sylius_stock_movement.controller.action.download_report
        _sylius:
            section: admin
            permission: true
            
setono_sylius_stock_movement_admin_report_send:
    path: /reports/send/{id}
    methods: [GET]
    defaults:
        _controller: setono_sylius_stock_movement.controller.action.send_report
        _sylius:
            section: admin
            permission: true
            
setono_sylius_stock_movement_admin_report_revalidate:
    path: /reports/revalidate/{id}
    methods: [GET]
    defaults:
        _controller: setono_sylius_stock_movement.controller.action.revalidate
        _sylius:
            section: admin
            permission: true
