setono_sylius_stock_admin_api_stock_movement:
    resource: |
        alias: setono_sylius_stock.stock_movement
        section: admin_api
        form: Setono\SyliusStockPlugin\Form\Type\Api\StockMovementType
        serialization_version: $version
    type: sylius.resource_api
