sylius_grid:
    grids:
        setono_sylius_stock_movement_admin_report_configuration:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_stock_movement.model.report_configuration.class%"
            fields:
                name:
                    type: string
                    label: setono_sylius_stock_movement.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    process:
                        type: process
                        label: setono_sylius_stock_movement.ui.process
                        options:
                            link:
                                route: setono_sylius_stock_movement_admin_report_configuration_process
                                parameters:
                                    id: resource.id
