sylius_grid:
    grids:
        setono_sylius_stock_movement_admin_stock_movement:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_stock_movement.model.stock_movement.class%"
            fields:
                createdAt:
                    type: datetime
                    label: setono_sylius_stock_movement.ui.created_at
                    options:
                        format: d-m-Y H:i:s
                quantity:
                    type: string
                    label: setono_sylius_stock_movement.ui.quantity
                variant:
                    type: string
                    label: setono_sylius_stock_movement.ui.variant
                price:
                    type: twig
                    label: setono_sylius_stock_movement.ui.price
                    options:
                        template: "@SetonoSyliusStockMovementPlugin/Admin/Grid/Field/money.html.twig"
                convertedPrice:
                    type: twig
                    label: setono_sylius_stock_movement.ui.converted_price
                    options:
                        template: "@SetonoSyliusStockMovementPlugin/Admin/Grid/Field/money.html.twig"
                reference:
                    type: string
                    label: setono_sylius_stock_movement.ui.reference
