sylius_grid:
    grids:
        setono_sylius_stock_movement_admin_report:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_stock_movement.model.report.class%"
            fields:
                id:
                    type: string
                    label: setono_sylius_stock_movement.ui.id
                reportConfiguration:
                    type: string
                    label: setono_sylius_stock_movement.ui.report_configuration
                createdAt:
                    type: datetime
                    label: setono_sylius_stock_movement.ui.created_at
                    options:
                        format: d-m-Y H:i:s
            actions:
                item:
                    show:
                        type: show
