sylius_grid:
    grids:
        setono_sylius_stock_admin_stock_movement_report_configuration:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_stock.model.stock_movement_report_configuration.class%"
            fields:
                name:
                    type: string
                    label: setono_sylius_stock.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        setono_sylius_stock_admin_stock_movement_report:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_stock.model.stock_movement_report.class%"
            fields:
                id:
                    type: string
                    label: setono_sylius_stock.ui.id
            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                        
sylius_mailer:
    emails:
        report:
            template: '@SetonoSyliusStockPlugin:Email:report.html.twig'
