setono_sylius_stock_movement_admin:
    resource: "routing/admin.yaml"
    prefix: /admin
    
setono_sylius_stock_movement_admin_api:
    resource: "routing/admin_api.yaml"
    prefix: /api/v{version}
