imports:
    - "@SetonoSyliusStockMovementPlugin/Resources/config/grids/setono_sylius_stock_movement_admin_report.yaml"
    - "@SetonoSyliusStockMovementPlugin/Resources/config/grids/setono_sylius_stock_movement_admin_report_configuration.yaml"
    - "@SetonoSyliusStockMovementPlugin/Resources/config/grids/setono_sylius_stock_movement_admin_stock_movement.yaml"

sylius_grid:
    templates:
        action:
            process: "@SetonoSyliusStockMovementPlugin/Admin/Grid/Action/process.html.twig"

flysystem:
    storages:
        setono_sylius_stock_movement.storage.local.report:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/setono_sylius_stock_movement/report'

framework:
    messenger:
        buses:
            setono_sylius_stock_movement.command_bus: ~

jms_serializer:
    metadata:
        directories:
            setono-sylius-stock-movement:
                namespace_prefix: "Setono\\SyliusStockMovementPlugin\\Model"
                path: "@SetonoSyliusStockMovementPlugin/Resources/config/serializer"
            money:
                namespace_prefix: "Money"
                path: "@SetonoSyliusStockMovementPlugin/Resources/config/serializer"

sylius_mailer:
    emails:
        setono_sylius_stock_movement_report:
            subject: Stock movement report
            template: '@SetonoSyliusStockMovementPlugin/Email/report.html.twig'
