Money\Money:
    exclusion_policy: ALL
    xml_root_name: money
    properties:
        amount:
            expose: true
            type: integer
            groups: [Default]
        currency:
            expose: true
            type: string
            groups: [Default]
