Setono\SyliusStockMovementPlugin\Model\StockMovement:
    exclusion_policy: ALL
    xml_root_name: stock-movement
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        quantity:
            expose: true
            type: integer
            groups: [Default, Detailed]
        price:
            expose: true
            groups: [Default, Detailed]
        convertedPrice:
            expose: true
            groups: [Default, Detailed]
        createdAt:
            expose: true
            groups: [Default, Detailed]
    virtual_properties:
        getVariantCode:
            serialized_name: variant
            groups: [Default, Detailed]
#    relations:
#        -   rel: self
#            href:
#                route: setono_sylius_brand_admin_api_brand_show
#                parameters:
#                    code: expr(object.getCode())
#                    version: 1
