Setono\SyliusStockMovementPlugin\Model\StockMovement:
    exclusion_policy: ALL
    xml_root_name: stock-movement
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        quantity:
            expose: true
            type: integer
            groups: [Default, Detailed]
        createdAt:
            expose: true
            groups: [Default, Detailed]
    virtual_properties:
        getVariantCode:
            serialized_name: variant
            groups: [Default, Detailed]
